"""
Notifications Router
Sends transactional emails via SendGrid (anomaly alerts, lead updates, meeting briefs).
"""

import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, EmailStr
from config import settings

router = APIRouter(prefix="/notifications", tags=["Notifications"])
logger = logging.getLogger("AEGIS_Notifications")


class EmailPayload(BaseModel):
    to_email: str
    subject: str
    body: str
    from_name: str = "AEGIS Intelligence Platform"


class AnomalyAlertPayload(BaseModel):
    to_email: str
    anomaly_id: str
    description: str
    severity: str = "High"


class MeetingBriefPayload(BaseModel):
    to_email: str
    lead_name: str
    meeting_time: str
    brief_html: str


def _send_email(to: str, subject: str, html_content: str) -> bool:
    """Send email via SendGrid. Returns True on success."""
    if not settings.SENDGRID_API_KEY:
        logger.warning("SENDGRID_API_KEY not configured — email not sent.")
        return False
    try:
        import sendgrid
        from sendgrid.helpers.mail import Mail, To, From

        sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
        message = Mail(
            from_email=From("noreply@aegis-ai.com", "AEGIS Platform"),
            to_emails=To(to),
            subject=subject,
            html_content=html_content,
        )
        resp = sg.client.mail.send.post(request_body=message.get())
        if resp.status_code in (200, 202):
            logger.info("Email sent to %s [status=%d]", to, resp.status_code)
            return True
        logger.error("SendGrid error: %d - %s", resp.status_code, resp.body)
        return False
    except Exception as e:
        logger.error("SendGrid exception: %s", e)
        return False


@router.post("/send")
async def send_custom_email(payload: EmailPayload):
    """Send a custom notification email."""
    html = f"<h2>{payload.subject}</h2><p>{payload.body}</p><hr><p><em>Sent by AEGIS Intelligence Platform</em></p>"
    success = _send_email(payload.to_email, payload.subject, html)
    if not success:
        raise HTTPException(status_code=502, detail="Failed to send email. Check SENDGRID_API_KEY.")
    return {"status": "sent", "to": payload.to_email}


@router.post("/anomaly-alert")
async def send_anomaly_alert(payload: AnomalyAlertPayload):
    """Send a financial anomaly alert to the Finance Manager."""
    subject = f"⚠️ AEGIS Anomaly Alert [{payload.severity}]: {payload.anomaly_id}"
    html = f"""
    <div style="font-family:sans-serif;max-width:600px;margin:auto;border:1px solid #e0e0e0;border-radius:8px;overflow:hidden;">
      <div style="background:#1a1a2e;padding:20px 30px;">
        <h1 style="color:#a78bfa;margin:0;font-size:22px;">⚠️ AEGIS Anomaly Alert</h1>
      </div>
      <div style="padding:30px;">
        <table style="width:100%;border-collapse:collapse;">
          <tr><td style="color:#555;padding:8px 0;font-weight:bold;">Anomaly ID</td><td>{payload.anomaly_id}</td></tr>
          <tr><td style="color:#555;padding:8px 0;font-weight:bold;">Severity</td><td><span style="color:{'#ef4444' if payload.severity=='High' else '#f59e0b'}">{payload.severity}</span></td></tr>
          <tr><td style="color:#555;padding:8px 0;font-weight:bold;">Details</td><td>{payload.description}</td></tr>
        </table>
        <p style="margin-top:20px;color:#666;">Please log into AEGIS dashboard to review and take action.</p>
      </div>
    </div>
    """
    success = _send_email(payload.to_email, subject, html)
    if not success:
        raise HTTPException(status_code=502, detail="Failed to send anomaly alert.")
    return {"status": "alert_sent", "anomaly_id": payload.anomaly_id}


@router.post("/meeting-brief")
async def send_meeting_brief(payload: MeetingBriefPayload):
    """Email an AI-generated meeting brief to the sales rep."""
    subject = f"📋 AEGIS Meeting Brief: {payload.lead_name} — {payload.meeting_time}"
    html = f"""
    <div style="font-family:sans-serif;max-width:600px;margin:auto;border:1px solid #e0e0e0;border-radius:8px;overflow:hidden;">
      <div style="background:#1a1a2e;padding:20px 30px;">
        <h1 style="color:#34d399;margin:0;font-size:22px;">📋 Meeting Brief</h1>
        <p style="color:#94a3b8;margin:6px 0 0;">{payload.lead_name} &bull; {payload.meeting_time}</p>
      </div>
      <div style="padding:30px;">
        {payload.brief_html}
        <hr style="border:none;border-top:1px solid #e0e0e0;margin:20px 0;">
        <p style="color:#999;font-size:12px;">Generated by AEGIS Sales Agent &bull; Powered by Llama 3.3 70B</p>
      </div>
    </div>
    """
    success = _send_email(payload.to_email, subject, html)
    if not success:
        raise HTTPException(status_code=502, detail="Failed to send meeting brief.")
    return {"status": "brief_sent", "lead": payload.lead_name}
