"use client";

import React from "react";
import { Table, FileText, CheckCircle2, AlertCircle } from "lucide-react";

interface AgentDataTableProps {
  title: string;
  agentName: string;
  data: Record<string, any> | Array<Record<string, any>>;
}

export const AgentDataTable: React.FC<AgentDataTableProps> = ({
  title,
  agentName,
  data,
}) => {
  const isArray = Array.isArray(data);

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-2xl">
      {/* Table Header */}
      <div className="px-6 py-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-teal-600/20 border border-teal-500/30 flex items-center justify-center text-teal-400">
            <Table size={20} />
          </div>
          <div>
            <h3 className="font-semibold text-slate-100">{title}</h3>
            <p className="text-xs text-slate-400">Generated by {agentName}</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 text-xs text-teal-400 bg-teal-950/40 border border-teal-800/40 px-3 py-1 rounded-full">
          <CheckCircle2 size={13} />
          <span>Structured Output</span>
        </div>
      </div>

      {/* Content Area */}
      <div className="p-6 overflow-x-auto">
        {isArray && data.length > 0 ? (
          <table className="w-full text-left border-collapse text-sm">
            <thead>
              <tr className="border-b border-slate-800 bg-slate-950/60 text-slate-400 text-xs font-semibold uppercase tracking-wider">
                {Object.keys(data[0]).map((key) => (
                  <th key={key} className="py-3 px-4">
                    {key.replace(/_/g, " ")}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-slate-300">
              {data.map((row, idx) => (
                <tr key={idx} className="hover:bg-slate-800/40 transition-colors">
                  {Object.values(row).map((val: any, cellIdx) => (
                    <td key={cellIdx} className="py-3 px-4">
                      {typeof val === "object" ? JSON.stringify(val) : String(val)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        ) : typeof data === "object" && data !== null ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {Object.entries(data).map(([key, val]) => (
              <div
                key={key}
                className="p-4 bg-slate-950/60 border border-slate-800 rounded-lg flex flex-col justify-between"
              >
                <span className="text-xs text-slate-400 font-medium uppercase tracking-wider mb-1">
                  {key.replace(/_/g, " ")}
                </span>
                <span className="text-slate-100 font-semibold break-words">
                  {typeof val === "object" ? (
                    <pre className="text-xs bg-slate-900 p-2 rounded text-slate-300 overflow-x-auto">
                      {JSON.stringify(val, null, 2)}
                    </pre>
                  ) : (
                    String(val)
                  )}
                </span>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-4 bg-slate-950 text-slate-400 text-sm rounded-lg flex items-center gap-2">
            <AlertCircle size={16} />
            <span>No tabular data available.</span>
          </div>
        )}
      </div>
    </div>
  );
};
